{% set version = '2.18' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-simdesign
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/SimDesign_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SimDesign/SimDesign_{{ version }}.tar.gz
  sha256: 5563e26f0bb53e05261438d862bc6b57ff4cb88fe099d5a802a85f7747bc7877

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r.utils
    - r-rpushbullet
    - r-beepr
    - r-dplyr
    - r-future
    - r-future.apply
    - r-parallelly
    - r-pbapply >=1.3_0
    - r-progressr
    - r-sessioninfo
    - r-snow
    - r-testthat
  run:
    - r-base
    - r-r.utils
    - r-rpushbullet
    - r-beepr
    - r-dplyr
    - r-future
    - r-future.apply
    - r-parallelly
    - r-pbapply >=1.3_0
    - r-progressr
    - r-sessioninfo
    - r-snow
    - r-testthat

test:
  commands:
    - $R -e "library('SimDesign')"           # [not win]
    - "\"%R%\" -e \"library('SimDesign')\""  # [win]

about:
  home: http://philchalmers.github.io/SimDesign/, https://github.com/philchalmers/SimDesign/wiki
  license: GPL-2.0-or-later
  summary: Provides tools to safely and efficiently organize and execute Monte Carlo simulation
    experiments in R. The package controls the structure and back-end of Monte Carlo
    simulation experiments by utilizing a generate-analyse-summarise workflow. The workflow
    safeguards against common simulation coding issues, such as automatically re-simulating
    non-convergent results, prevents inadvertently overwriting simulation files, catches
    error and warning messages during execution, implicitly supports parallel processing
    with high-quality random number generation, and provides tools for managing high-performance
    computing (HPC) array jobs submitted to schedulers such as SLURM. For a pedagogical
    introduction to the package see Sigal and Chalmers (2016) <doi:10.1080/10691898.2016.1246953>.
    For a more in-depth overview of the package and its design philosophy see Chalmers
    and Adkins (2020) <doi:10.20982/tqmp.16.4.p248>.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
