{% set version = "2.21" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-simdesign
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/SimDesign_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SimDesign/SimDesign_{{ version }}.tar.gz
  sha256: fba1ca9c6356060d89ff19efbfdac738c188f919d3b3b996244dd334f4e407fc

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r.utils
    - r-beepr
    - r-clipr
    - r-codetools
    - r-dplyr
    - r-future
    - r-future.apply
    - r-parallelly
    - r-pbapply >=1.3_0
    - r-progressr
    - r-sessioninfo
    - r-testthat
  run:
    - r-base
    - r-r.utils
    - r-beepr
    - r-clipr
    - r-codetools
    - r-dplyr
    - r-future
    - r-future.apply
    - r-parallelly
    - r-pbapply >=1.3_0
    - r-progressr
    - r-sessioninfo
    - r-testthat

test:
  commands:
    - $R -e "library('SimDesign')"           # [not win]
    - "\"%R%\" -e \"library('SimDesign')\""  # [win]

about:
  home: https://philchalmers.github.io/SimDesign/
  dev_url: https://github.com/philchalmers/SimDesign
  doc_url: https://github.com/philchalmers/SimDesign/wiki
  license: GPL-2.0-or-later
  summary: Provides tools to safely and efficiently organize and execute Monte Carlo simulation experiments in R. The package controls the structure and back-end of Monte Carlo simulation experiments by utilizing a generate-analyse-summarise workflow. The workflow safeguards against common simulation coding issues, such
    as automatically re-simulating non-convergent results, prevents inadvertently overwriting simulation files, catches error and warning messages during execution, implicitly supports parallel processing with high-quality random number generation, and provides tools for managing high-performance computing (HPC) array jobs
    submitted to schedulers such as SLURM. For a pedagogical introduction to the package see Sigal and Chalmers (2016) <doi:10.1080/10691898.2016.1246953>. For a more in-depth overview of the package and its design philosophy see Chalmers and Adkins (2020) <doi:10.20982/tqmp.16.4.p248>.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
